apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: "LHRS"
      defaultBucket: "telemetry_main"
    secureJsonData:
      token: "w00zXEpihSphLEaSeV2N_TPFzYiSOi_ixW21jwQBLUdC1kDod5682SnU30kldIsZNWEHePmtXBxsXynsRoAd5g=="
