services:
  influxdb:
    image: influxdb:3-core
    container_name: influxdb
    ports:
      - "8181:8181"  # v3 default port
    command:
      - influxdb3
      - serve
      - --node-id=node1
      - --object-store=file
      - --data-dir=/var/lib/influxdb3/data
      - --plugin-dir=/var/lib/influxdb3/plugins
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: lhrs2025!
      DOCKER_INFLUXDB_INIT_ORG: LHRS
    volumes:
      - ./influx_data:/var/lib/influxdb3/data
      - ./influxdb-init.sh:/docker-entrypoint-initdb.d/influxdb-init.sh:ro
      - ./provisions:/shared-provisioning
      - ./plugins:/var/lib/influxdb3/plugins
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.2.3
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: lhrs2025!

      # Auto configure Grafana InfluxDB datasource
      GF_PROVISIONING_ENABLED: "true"

    volumes:
      - grafana_data:/var/lib/grafana
      - ./provisions:/etc/grafana/provisioning/
    restart: unless-stopped
    entrypoint: [ "/bin/sh", "-c" ]
    command: >
      "echo '>>> Waiting for Grafana provisioning files...'; \
       while [ ! -f /etc/grafana/provisioning/datasources/influx.yml ]; do sleep 1; done; \
       /run.sh"


volumes:
  grafana_data: