{
 "title": "HighNoon — Overview",
 "tags": [
  "HighNoon",
  "overview"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "panels": [
  { "title": "Vehicle State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "VCU FSM State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "channel": "stream/telemetry/18", "filter": { "fields": [ "VCU_FSM_State" ] }, "buffer": 1 }
   ]
  },
  {
   "title": "Motor Ready",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "channel": "stream/telemetry/18", "filter": { "fields": [ "Motor_Ready" ] }, "buffer": 1 }
   ]
  },
  {
   "title": "Driver Inputs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "channel": "stream/telemetry/60",
     "filter": {
      "fields": [
       "Gear_Forward",
       "Gear_Neutral",
       "Gear_Reverse",
       "Ignition_Array",
       "Ignition_Motor",
       "Ignition_Off",
       "Cruise_Enable"
      ]
     },
     "buffer": 1
    }
   ]
  },
  {
   "title": "Telemetry Heartbeat",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "channel": "stream/telemetry/700", "filter": { "fields": [ "Telemetry_Heartbeat" ] }, "buffer": 1 }
   ]
  },
  { "title": "Speed & Drive", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Wheel RPM FR",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "channel": "stream/telemetry/14A0", "filter": { "fields": [ "RPM" ] }, "buffer": 1 }
   ]
  },
  {
   "title": "Velocity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "channel": "stream/telemetry/14D0", "filter": { "fields": [ "RPM" ] }, "buffer": 1 },
    {
     "channel": "stream/telemetry/423",
     "filter": {
      "fields": [
       "MC_VehicleVelocity",
       "MC_MotorVelocity"
      ]
     },
     "buffer": 1
    }
   ]
  },
  {
   "title": "Driver Sensors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "channel": "stream/telemetry/2B0", "filter": { "fields": [ "LWS_Angle" ] }, "buffer": 1 },
    {
     "channel": "stream/telemetry/50",
     "filter": {
      "fields": [
       "AccelPedal_Main_Pos",
       "BrakePedal_Main_Pos"
      ]
     },
     "buffer": 1
    }
   ]
  },
  {
   "title": "Vehicle & Motor Velocity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry_main\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"423\")\n  |> filter(fn: (r) => r._field == \"MC_VehicleVelocity\")\n  |> filter(fn: (r) => r.vehicle == \"HighNoon\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    },
    {
     "query": "from(bucket: \"telemetry_main\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"423\")\n  |> filter(fn: (r) => r._field == \"MC_MotorVelocity\")\n  |> filter(fn: (r) => r.vehicle == \"HighNoon\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    }
   ]
  },
  {
   "title": "Wheel RPM",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry_main\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"14A0\")\n  |> filter(fn: (r) => r._field == \"RPM\")\n  |> filter(fn: (r) => r.vehicle == \"HighNoon\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    },
    {
     "query": "from(bucket: \"telemetry_main\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"14D0\")\n  |> filter(fn: (r) => r._field == \"RPM\")\n  |> filter(fn: (r) => r.vehicle == \"HighNoon\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    }
   ]
  },
  {
   "title": "Pedal Positions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry_main\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"50\")\n  |> filter(fn: (r) => r._field == \"AccelPedal_Main_Pos\")\n  |> filter(fn: (r) => r.vehicle == \"HighNoon\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    },
    {
     "query": "from(bucket: \"telemetry_main\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"50\")\n  |> filter(fn: (r) => r._field == \"BrakePedal_Main_Pos\")\n  |> filter(fn: (r) => r.vehicle == \"HighNoon\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    }
   ]
  },
  {
   "title": "Steering Angle",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry_main\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"2B0\")\n  |> filter(fn: (r) => r._field == \"LWS_Angle\")\n  |> filter(fn: (r) => r.vehicle == \"HighNoon\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    }
   ]
  },
  { "title": "Regen & Brake", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "VCU Regen Active",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "channel": "stream/telemetry/18", "filter": { "fields": [ "VCU_Regen_Active" ] }, "buffer": 1 }
   ]
  },
  {
   "title": "VCU Regen OK",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "channel": "stream/telemetry/18", "filter": { "fields": [ "VCU_Regen_OK" ] }, "buffer": 1 }
   ]
  },
  {
   "title": "Brake Pressure",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "pressurepsi" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "channel": "stream/telemetry/650", "filter": { "fields": [ "Brake_Pressure" ] }, "buffer": 1 }
   ]
  },
  { "title": "Currents", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Electrical",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "channel": "stream/telemetry/422",
     "filter": {
      "fields": [
       "MC_BusCurrent",
       "MC_BusVoltage"
      ]
     },
     "buffer": 1
    },
    {
     "channel": "stream/telemetry/426",
     "filter": {
      "fields": [
       "MC_Iq",
       "MC_Id"
      ]
     },
     "buffer": 1
    },
    { "channel": "stream/telemetry/A", "filter": { "fields": [ "Main_Battery_Current" ] }, "buffer": 1 }
   ]
  },
  {
   "title": "Pack Current",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry_main\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"A\")\n  |> filter(fn: (r) => r._field == \"Main_Battery_Current\")\n  |> filter(fn: (r) => r.vehicle == \"HighNoon\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    }
   ]
  },
  {
   "title": "Motor Bus Current & Voltage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry_main\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"422\")\n  |> filter(fn: (r) => r._field == \"MC_BusCurrent\")\n  |> filter(fn: (r) => r.vehicle == \"HighNoon\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    },
    {
     "query": "from(bucket: \"telemetry_main\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"422\")\n  |> filter(fn: (r) => r._field == \"MC_BusVoltage\")\n  |> filter(fn: (r) => r.vehicle == \"HighNoon\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    }
   ]
  },
  {
   "title": "Motor Current Vector (Iq / Id)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry_main\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"426\")\n  |> filter(fn: (r) => r._field == \"MC_Iq\")\n  |> filter(fn: (r) => r.vehicle == \"HighNoon\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    },
    {
     "query": "from(bucket: \"telemetry_main\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"426\")\n  |> filter(fn: (r) => r._field == \"MC_Id\")\n  |> filter(fn: (r) => r.vehicle == \"HighNoon\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    }
   ]
  },
  { "title": "Power & Battery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Pack Voltage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "channel": "stream/telemetry/1", "filter": { "fields": [ "Main_Battery_Voltage" ] }, "buffer": 1 }
   ]
  },
  {
   "title": "Pack Avg Temp",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "channel": "stream/telemetry/1", "filter": { "fields": [ "Main_Battery_Avg_Temperature" ] }, "buffer": 1 }
   ]
  },
  {
   "title": "Pack Power",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "v = from(bucket: \"telemetry_main\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._measurement == \"1\")\n  |> filter(fn: (r) => r._field == \"Main_Battery_Voltage\")\n  |> filter(fn: (r) => r.vehicle == \"HighNoon\")\n  |> group()\n  |> last()\n  |> map(fn: (r) => ({_time: now(), _value: r._value, _field: \"v\"}))\ni = from(bucket: \"telemetry_main\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._measurement == \"A\")\n  |> filter(fn: (r) => r._field == \"Main_Battery_Current\")\n  |> filter(fn: (r) => r.vehicle == \"HighNoon\")\n  |> group()\n  |> last()\n  |> map(fn: (r) => ({_time: now(), _value: r._value, _field: \"i\"}))\nunion(tables: [v, i])\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({_time: r._time, _value: r.v * r.i, _field: \"Power\"}))\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    }
   ]
  },
  {
   "title": "MC Bus Power",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry_main\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._measurement == \"422\")\n  |> filter(fn: (r) => r._field == \"MC_BusVoltage\" or r._field == \"MC_BusCurrent\")\n  |> filter(fn: (r) => r.vehicle == \"HighNoon\")\n  |> group(columns: [\"_field\"])\n  |> last()\n  |> map(fn: (r) => ({_time: now(), _value: r._value, _field: r._field}))\n  |> group()\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({_time: r._time, _value: r.MC_BusVoltage * r.MC_BusCurrent, _field: \"Power\"}))\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    }
   ]
  },
  {
   "title": "Pack Voltage & Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry_main\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"1\")\n  |> filter(fn: (r) => r._field == \"Main_Battery_Voltage\")\n  |> filter(fn: (r) => r.vehicle == \"HighNoon\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    },
    {
     "query": "from(bucket: \"telemetry_main\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"1\")\n  |> filter(fn: (r) => r._field == \"Main_Battery_Avg_Temperature\")\n  |> filter(fn: (r) => r.vehicle == \"HighNoon\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    }
   ]
  },
  {
   "title": "Pack Power",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "v = from(bucket: \"telemetry_main\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"1\")\n  |> filter(fn: (r) => r._field == \"Main_Battery_Voltage\")\n  |> filter(fn: (r) => r.vehicle == \"HighNoon\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({_time: r._time, _value: r._value, _field: \"v\"}))\n  |> group()\ni = from(bucket: \"telemetry_main\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"A\")\n  |> filter(fn: (r) => r._field == \"Main_Battery_Current\")\n  |> filter(fn: (r) => r.vehicle == \"HighNoon\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({_time: r._time, _value: r._value, _field: \"i\"}))\n  |> group()\nunion(tables: [v, i])\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) => exists r.v and exists r.i)\n  |> map(fn: (r) => ({_time: r._time, _value: r.v * r.i, _field: \"Pack_Power\"}))\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    }
   ]
  },
  { "title": "Temps (critical)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Cooling",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 75 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "channel": "stream/telemetry/501",
     "filter": {
      "fields": [
       "Coolant_Temperature_1",
       "Coolant_Temperature_2"
      ]
     },
     "buffer": 1
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 78 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "channel": "stream/telemetry/1", "filter": { "fields": [ "Main_Battery_Avg_Temperature" ] }, "buffer": 1 },
    {
     "channel": "stream/telemetry/42B",
     "filter": {
      "fields": [
       "MC_MotorTemp",
       "MC_HeatsinkTemp"
      ]
     },
     "buffer": 1
    },
    { "channel": "stream/telemetry/42C", "filter": { "fields": [ "MC_DspBoardTemp" ] }, "buffer": 1 }
   ]
  },
  {
   "title": "Critical Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry_main\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"42B\")\n  |> filter(fn: (r) => r._field == \"MC_MotorTemp\")\n  |> filter(fn: (r) => r.vehicle == \"HighNoon\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    },
    {
     "query": "from(bucket: \"telemetry_main\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"42B\")\n  |> filter(fn: (r) => r._field == \"MC_HeatsinkTemp\")\n  |> filter(fn: (r) => r.vehicle == \"HighNoon\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    },
    {
     "query": "from(bucket: \"telemetry_main\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"42C\")\n  |> filter(fn: (r) => r._field == \"MC_DspBoardTemp\")\n  |> filter(fn: (r) => r.vehicle == \"HighNoon\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    },
    {
     "query": "from(bucket: \"telemetry_main\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"501\")\n  |> filter(fn: (r) => r._field == \"Coolant_Temperature_1\")\n  |> filter(fn: (r) => r.vehicle == \"HighNoon\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    },
    {
     "query": "from(bucket: \"telemetry_main\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"501\")\n  |> filter(fn: (r) => r._field == \"Coolant_Temperature_2\")\n  |> filter(fn: (r) => r.vehicle == \"HighNoon\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    },
    {
     "query": "from(bucket: \"telemetry_main\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"1\")\n  |> filter(fn: (r) => r._field == \"Main_Battery_Avg_Temperature\")\n  |> filter(fn: (r) => r.vehicle == \"HighNoon\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    }
   ]
  },
  { "title": "Contactors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "Contactors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 89 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "channel": "stream/telemetry/1",
     "filter": {
      "fields": [
       "HV_Plus_Contactor_State",
       "HV_Minus_Contactor_State",
       "Array_Contactor_State",
       "Array_Precharge_Contactor_State"
      ]
     },
     "buffer": 1
    },
    {
     "channel": "stream/telemetry/18",
     "filter": {
      "fields": [
       "Motor_Contactor_State",
       "Motor_Precharge_Contactor_State"
      ]
     },
     "buffer": 1
    }
   ]
  },
  {
   "title": "Contactor States (timeline)",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 93 },
   "targets": [
    {
     "query": "from(bucket: \"telemetry_main\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"1\")\n  |> filter(fn: (r) => r._field == \"HV_Plus_Contactor_State\" or r._field == \"HV_Minus_Contactor_State\" or r._field == \"Array_Contactor_State\" or r._field == \"Array_Precharge_Contactor_State\")\n  |> filter(fn: (r) => r.vehicle == \"HighNoon\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    },
    {
     "query": "from(bucket: \"telemetry_main\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"18\")\n  |> filter(fn: (r) => r._field == \"Motor_Contactor_State\" or r._field == \"Motor_Precharge_Contactor_State\")\n  |> filter(fn: (r) => r.vehicle == \"HighNoon\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    }
   ]
  },
  { "title": "Faults summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 } },
  {
   "title": "Faults",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 103 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "channel": "stream/telemetry/1", "filter": { "fields": [ "BPS_Fault" ] }, "buffer": 1 },
    {
     "channel": "stream/telemetry/18",
     "filter": {
      "fields": [
       "VCU_BPS_FAULT_DETECTED",
       "VCU_CONTROLS_FAULT_DETECTED",
       "VCU_MTR_FAULT_DETECTED",
       "VCU_PEDALS_FAULT_DETECTED",
       "VCU_STEERING_FAULT_DETECTED"
      ]
     },
     "buffer": 1
    },
    { "channel": "stream/telemetry/19", "filter": { "fields": [ "Controls_Leader_Fault" ] }, "buffer": 1 }
   ]
  },
  {
   "title": "BPS Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 107 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "channel": "stream/telemetry/1",
     "filter": {
      "fields": [
       "BPS_Charge_OK",
       "BPS_Regen_OK"
      ]
     },
     "buffer": 1
    }
   ]
  },
  {
   "title": "MC Faults",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 110 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "channel": "stream/telemetry/421",
     "filter": {
      "fields": [
       "MC_FAULT_HardwareOverCurrent",
       "MC_FAULT_MotorOverSpeed",
       "MC_FAULT_SoftwareOverCurrent",
       "MC_FAULT_DcBusOverVoltage"
      ]
     },
     "buffer": 1
    }
   ]
  },
  {
   "title": "MC Limits",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 113 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "channel": "stream/telemetry/421",
     "filter": {
      "fields": [
       "MC_LIMIT_MotorCurrent",
       "MC_LIMIT_Velocity",
       "MC_LIMIT_BusCurrent"
      ]
     },
     "buffer": 1
    }
   ]
  },
  {
   "title": "MC Faults & Limits (timeline)",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 116 },
   "targets": [
    {
     "query": "from(bucket: \"telemetry_main\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"421\")\n  |> filter(fn: (r) => r._field == \"MC_FAULT_HardwareOverCurrent\" or r._field == \"MC_FAULT_MotorOverSpeed\" or r._field == \"MC_FAULT_SoftwareOverCurrent\" or r._field == \"MC_FAULT_DcBusOverVoltage\" or r._field == \"MC_LIMIT_MotorCurrent\" or r._field == \"MC_LIMIT_Velocity\" or r._field == \"MC_LIMIT_BusCurrent\")\n  |> filter(fn: (r) => r.vehicle == \"HighNoon\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    }
   ]
  },
  { "title": "Data freshness", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 126 } },
  {
   "title": "Pack V age",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry_main\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._measurement == \"1\")\n  |> filter(fn: (r) => r._field == \"Main_Battery_Voltage\")\n  |> filter(fn: (r) => r.vehicle == \"HighNoon\")\n  |> group()\n  |> last()\n  |> map(fn: (r) => ({ _value: (float(v: uint(v: now())) - float(v: uint(v: r._time))) / 1000000000.0 }))\n  |> keep(columns: [\"_value\"])"
    }
   ]
  },
  {
   "title": "Bus I age",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry_main\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._measurement == \"422\")\n  |> filter(fn: (r) => r._field == \"MC_BusCurrent\")\n  |> filter(fn: (r) => r.vehicle == \"HighNoon\")\n  |> group()\n  |> last()\n  |> map(fn: (r) => ({ _value: (float(v: uint(v: now())) - float(v: uint(v: r._time))) / 1000000000.0 }))\n  |> keep(columns: [\"_value\"])"
    }
   ]
  },
  {
   "title": "FSM age",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry_main\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._measurement == \"18\")\n  |> filter(fn: (r) => r._field == \"VCU_FSM_State\")\n  |> filter(fn: (r) => r.vehicle == \"HighNoon\")\n  |> group()\n  |> last()\n  |> map(fn: (r) => ({ _value: (float(v: uint(v: now())) - float(v: uint(v: r._time))) / 1000000000.0 }))\n  |> keep(columns: [\"_value\"])"
    }
   ]
  },
  {
   "title": "Pack I age",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry_main\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._measurement == \"A\")\n  |> filter(fn: (r) => r._field == \"Main_Battery_Current\")\n  |> filter(fn: (r) => r.vehicle == \"HighNoon\")\n  |> group()\n  |> last()\n  |> map(fn: (r) => ({ _value: (float(v: uint(v: now())) - float(v: uint(v: r._time))) / 1000000000.0 }))\n  |> keep(columns: [\"_value\"])"
    }
   ]
  }
 ]
}