{
 "title": "HighNoon — Driver, Controls & Lighting",
 "tags": [
  "HighNoon",
  "controls",
  "lighting"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "panels": [
  { "title": "Driver Inputs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Driver Inputs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "channel": "stream/telemetry/60",
     "filter": {
      "fields": [
       "Ignition_Array",
       "Ignition_Motor",
       "Ignition_Off",
       "Cruise_Enable",
       "Cruise_Set",
       "Gear_Forward",
       "Gear_Neutral",
       "Gear_Reverse"
      ]
     },
     "buffer": 1
    }
   ]
  },
  {
   "title": "Driver Switches",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "channel": "stream/telemetry/60",
     "filter": {
      "fields": [
       "Hazard_Pressed",
       "Horn_Pressed",
       "Blinker_Left",
       "Blinker_Right",
       "PushToTalk_Pressed",
       "Regen_Activate",
       "Regen_Enable"
      ]
     },
     "buffer": 1
    }
   ]
  },
  {
   "title": "Driver Inputs Timeline",
   "type": "state-timeline",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"telemetry_main\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"60\")\n  |> filter(fn: (r) => r._field == \"Ignition_Array\" or r._field == \"Ignition_Motor\" or r._field == \"Ignition_Off\" or r._field == \"Cruise_Enable\" or r._field == \"Cruise_Set\" or r._field == \"Gear_Forward\" or r._field == \"Gear_Neutral\" or r._field == \"Gear_Reverse\" or r._field == \"Hazard_Pressed\" or r._field == \"Horn_Pressed\" or r._field == \"Blinker_Left\" or r._field == \"Blinker_Right\" or r._field == \"PushToTalk_Pressed\" or r._field == \"Regen_Activate\" or r._field == \"Regen_Enable\")\n  |> filter(fn: (r) => r.vehicle == \"HighNoon\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    }
   ]
  },
  { "title": "VCU FSM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "VCU Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "channel": "stream/telemetry/18",
     "filter": {
      "fields": [
       "VCU_FSM_State",
       "VCU_Regen_Active",
       "VCU_FSM_INP_BRAKE",
       "VCU_FSM_INP_PCHG_OK",
       "VCU_FSM_INP_REGEN_REQ",
       "VCU_FSM_INP_REGEN_RDY",
       "VCU_FSM_INP_FORWARD",
       "VCU_FSM_INP_NEUTRAL",
       "VCU_FSM_INP_REVERSE"
      ]
     },
     "buffer": 1
    }
   ]
  },
  {
   "title": "FSM Cruise Req",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "channel": "stream/telemetry/18", "filter": { "fields": [ "VCU_FSM_INP_CRUISE_REQ" ] }, "buffer": 1 }
   ]
  },
  {
   "title": "FSM Regen En",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "channel": "stream/telemetry/18", "filter": { "fields": [ "VCU_FSM_INP_REGEN_ENABLE" ] }, "buffer": 1 }
   ]
  },
  {
   "title": "VCU FSM Timeline",
   "type": "state-timeline",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "query": "from(bucket: \"telemetry_main\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"18\")\n  |> filter(fn: (r) => r._field == \"VCU_FSM_State\" or r._field == \"VCU_FSM_INP_BRAKE\" or r._field == \"VCU_FSM_INP_PCHG_OK\" or r._field == \"VCU_FSM_INP_CRUISE_REQ\" or r._field == \"VCU_FSM_INP_REGEN_REQ\" or r._field == \"VCU_FSM_INP_REGEN_ENABLE\" or r._field == \"VCU_FSM_INP_REGEN_RDY\" or r._field == \"VCU_FSM_INP_FORWARD\" or r._field == \"VCU_FSM_INP_NEUTRAL\" or r._field == \"VCU_FSM_INP_REVERSE\")\n  |> filter(fn: (r) => r.vehicle == \"HighNoon\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    }
   ]
  },
  { "title": "VCU Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Motor_Ready",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "channel": "stream/telemetry/18", "filter": { "fields": [ "Motor_Ready" ] }, "buffer": 1 }
   ]
  },
  {
   "title": "Contactors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "channel": "stream/telemetry/18",
     "filter": {
      "fields": [
       "Motor_Precharge_Contactor_State",
       "Motor_Contactor_State"
      ]
     },
     "buffer": 1
    }
   ]
  },
  {
   "title": "VCU Faults",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "channel": "stream/telemetry/18",
     "filter": {
      "fields": [
       "VCU_Driver_Input_Watchdog",
       "VCU_Pedals_Watchdog",
       "VCU_BPS_Watchdog",
       "VCU_Steering_Angle_Watchdog",
       "VCU_BPS_FAULT_DETECTED",
       "VCU_CONTROLS_FAULT_DETECTED",
       "VCU_MTR_FAULT_DETECTED",
       "VCU_PEDALS_FAULT_DETECTED",
       "VCU_STEERING_FAULT_DETECTED"
      ]
     },
     "buffer": 1
    }
   ]
  },
  {
   "title": "VCU Health Timeline",
   "type": "state-timeline",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "query": "from(bucket: \"telemetry_main\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"18\")\n  |> filter(fn: (r) => r._field == \"Motor_Ready\" or r._field == \"Motor_Precharge_Contactor_State\" or r._field == \"Motor_Contactor_State\" or r._field == \"VCU_Driver_Input_Watchdog\" or r._field == \"VCU_Pedals_Watchdog\" or r._field == \"VCU_BPS_Watchdog\" or r._field == \"VCU_Steering_Angle_Watchdog\" or r._field == \"VCU_BPS_FAULT_DETECTED\" or r._field == \"VCU_CONTROLS_FAULT_DETECTED\" or r._field == \"VCU_MTR_FAULT_DETECTED\" or r._field == \"VCU_PEDALS_FAULT_DETECTED\" or r._field == \"VCU_STEERING_FAULT_DETECTED\")\n  |> filter(fn: (r) => r.vehicle == \"HighNoon\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    }
   ]
  },
  { "title": "Pedals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Accel Main",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "channel": "stream/telemetry/50", "filter": { "fields": [ "AccelPedal_Main_Pos" ] }, "buffer": 1 }
   ]
  },
  {
   "title": "Accel Redundant",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "channel": "stream/telemetry/50", "filter": { "fields": [ "AccelPedal_Redundant_Pos" ] }, "buffer": 1 }
   ]
  },
  {
   "title": "Brake Main",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "channel": "stream/telemetry/50", "filter": { "fields": [ "BrakePedal_Main_Pos" ] }, "buffer": 1 }
   ]
  },
  {
   "title": "Brake Redundant",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "channel": "stream/telemetry/50", "filter": { "fields": [ "BrakePedal_Redundant_Pos" ] }, "buffer": 1 }
   ]
  },
  {
   "title": "Brake Pressure 1",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "pressurepsi" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "channel": "stream/telemetry/650", "filter": { "fields": [ "Brake_Pressure" ] }, "buffer": 1 }
   ]
  },
  {
   "title": "Brake Pressure 2",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "pressurepsi" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "channel": "stream/telemetry/651", "filter": { "fields": [ "Brake_Pressure" ] }, "buffer": 1 }
   ]
  },
  {
   "title": "Pedal Positions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry_main\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"50\")\n  |> filter(fn: (r) => r._field == \"AccelPedal_Main_Pos\")\n  |> filter(fn: (r) => r.vehicle == \"HighNoon\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    },
    {
     "query": "from(bucket: \"telemetry_main\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"50\")\n  |> filter(fn: (r) => r._field == \"AccelPedal_Redundant_Pos\")\n  |> filter(fn: (r) => r.vehicle == \"HighNoon\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    },
    {
     "query": "from(bucket: \"telemetry_main\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"50\")\n  |> filter(fn: (r) => r._field == \"BrakePedal_Main_Pos\")\n  |> filter(fn: (r) => r.vehicle == \"HighNoon\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    },
    {
     "query": "from(bucket: \"telemetry_main\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"50\")\n  |> filter(fn: (r) => r._field == \"BrakePedal_Redundant_Pos\")\n  |> filter(fn: (r) => r.vehicle == \"HighNoon\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    }
   ]
  },
  {
   "title": "Brake Pressure (PSI)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "pressurepsi" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry_main\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"650\")\n  |> filter(fn: (r) => r._field == \"Brake_Pressure\")\n  |> filter(fn: (r) => r.vehicle == \"HighNoon\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    },
    {
     "query": "from(bucket: \"telemetry_main\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"651\")\n  |> filter(fn: (r) => r._field == \"Brake_Pressure\")\n  |> filter(fn: (r) => r.vehicle == \"HighNoon\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    }
   ]
  },
  {
   "title": "Pedal ADC Raw",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry_main\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"754\")\n  |> filter(fn: (r) => r._field == \"AccelPedal_Main_ADC\")\n  |> filter(fn: (r) => r.vehicle == \"HighNoon\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    },
    {
     "query": "from(bucket: \"telemetry_main\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"754\")\n  |> filter(fn: (r) => r._field == \"AccelPedal_Redundant_ADC\")\n  |> filter(fn: (r) => r.vehicle == \"HighNoon\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    },
    {
     "query": "from(bucket: \"telemetry_main\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"753\")\n  |> filter(fn: (r) => r._field == \"BrakePedal_Main_ADC\")\n  |> filter(fn: (r) => r.vehicle == \"HighNoon\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    },
    {
     "query": "from(bucket: \"telemetry_main\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"753\")\n  |> filter(fn: (r) => r._field == \"BrakePedal_Redundant_ADC\")\n  |> filter(fn: (r) => r.vehicle == \"HighNoon\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    }
   ]
  },
  {
   "title": "Faults",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 95 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "channel": "stream/telemetry/50",
     "filter": {
      "fields": [
       "AccelPedal_Main_Fault",
       "AccelPedal_Redundant_Fault",
       "BrakePedal_Main_Fault",
       "BrakePedal_Redundant_Fault",
       "Brake_Pressure_1_Fault",
       "Brake_Pressure_2_Fault"
      ]
     },
     "buffer": 1
    }
   ]
  },
  { "title": "Steering", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 } },
  {
   "title": "Driver Sensors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 100 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "channel": "stream/telemetry/2B0",
     "filter": {
      "fields": [
       "LWS_Angle",
       "LWS_CalibrationStaus",
       "LWS_Trimming_Status"
      ]
     },
     "buffer": 1
    }
   ]
  },
  {
   "title": "Steering Angle",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 6, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry_main\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"2B0\")\n  |> filter(fn: (r) => r._field == \"LWS_Angle\")\n  |> filter(fn: (r) => r.vehicle == \"HighNoon\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    }
   ]
  },
  {
   "title": "Steering Speed (°/s)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry_main\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"2B0\")\n  |> filter(fn: (r) => r._field == \"LWS_Speed\")\n  |> filter(fn: (r) => r.vehicle == \"HighNoon\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    }
   ]
  },
  {
   "title": "LWS Fault",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 103 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "channel": "stream/telemetry/2B0", "filter": { "fields": [ "LWS_Fault" ] }, "buffer": 1 }
   ]
  },
  { "title": "Lighting Command", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 } },
  {
   "title": "Lighting Commands",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 110 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "channel": "stream/telemetry/660",
     "filter": {
      "fields": [
       "Lighting_Set_Headlights",
       "Lighting_Set_Left_Indicator",
       "Lighting_Set_Right_Indicator",
       "Lighting_Set_Brake",
       "Lighting_Set_BPS_Strobe",
       "Lighting_Set_Custom_Mode",
       "Lighting_Blink_Sync"
      ]
     },
     "buffer": 1
    }
   ]
  },
  {
   "title": "Lighting Command Timeline",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 114 },
   "targets": [
    {
     "query": "from(bucket: \"telemetry_main\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"660\")\n  |> filter(fn: (r) => r._field == \"Lighting_Set_Headlights\" or r._field == \"Lighting_Set_Left_Indicator\" or r._field == \"Lighting_Set_Right_Indicator\" or r._field == \"Lighting_Set_Brake\" or r._field == \"Lighting_Set_BPS_Strobe\" or r._field == \"Lighting_Set_Custom_Mode\" or r._field == \"Lighting_Blink_Sync\")\n  |> filter(fn: (r) => r.vehicle == \"HighNoon\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    }
   ]
  },
  { "title": "Lighting Boards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 124 } },
  {
   "title": "Front Fault",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 125 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "channel": "stream/telemetry/670", "filter": { "fields": [ "Lighting_Board_Fault" ] }, "buffer": 1 }
   ]
  },
  {
   "title": "Left Fault",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 125 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "channel": "stream/telemetry/671", "filter": { "fields": [ "Lighting_Board_Fault" ] }, "buffer": 1 }
   ]
  },
  {
   "title": "Rear Fault",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 125 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "channel": "stream/telemetry/672", "filter": { "fields": [ "Lighting_Board_Fault" ] }, "buffer": 1 }
   ]
  },
  {
   "title": "Right Fault",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 125 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "channel": "stream/telemetry/673", "filter": { "fields": [ "Lighting_Board_Fault" ] }, "buffer": 1 }
   ]
  },
  {
   "title": "Canopy Fault",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 125 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "channel": "stream/telemetry/674", "filter": { "fields": [ "Lighting_Board_Fault" ] }, "buffer": 1 }
   ]
  },
  {
   "title": "Ctrl Leader Fault",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 125 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "channel": "stream/telemetry/19", "filter": { "fields": [ "Controls_Leader_Fault" ] }, "buffer": 1 }
   ]
  },
  {
   "title": "Lighting",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 128 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "channel": "stream/telemetry/19",
     "filter": {
      "fields": [
       "LightingBoard_Front_Status",
       "LightingBoard_Left_Status",
       "LightingBoard_Right_Status",
       "LightingBoard_Rear_Status",
       "LightingBoard_Canopy_Status"
      ]
     },
     "buffer": 1
    }
   ]
  },
  {
   "title": "Lighting Front",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 132 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "channel": "stream/telemetry/670",
     "filter": {
      "fields": [
       "Light_CustomMode",
       "Light_Headlight",
       "Light_Left_Indicator",
       "Light_Right_Indicator",
       "Light_BPS_Strobe",
       "Light_Brakelight"
      ]
     },
     "buffer": 1
    }
   ]
  },
  {
   "title": "Lighting Left",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 136 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "channel": "stream/telemetry/671",
     "filter": {
      "fields": [
       "Light_CustomMode",
       "Light_Headlight",
       "Light_Left_Indicator",
       "Light_Right_Indicator",
       "Light_BPS_Strobe",
       "Light_Brakelight"
      ]
     },
     "buffer": 1
    }
   ]
  },
  {
   "title": "Lighting Rear",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 140 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "channel": "stream/telemetry/672",
     "filter": {
      "fields": [
       "Light_CustomMode",
       "Light_Headlight",
       "Light_Left_Indicator",
       "Light_Right_Indicator",
       "Light_BPS_Strobe",
       "Light_Brakelight"
      ]
     },
     "buffer": 1
    }
   ]
  },
  {
   "title": "Lighting Right",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 144 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "channel": "stream/telemetry/673",
     "filter": {
      "fields": [
       "Light_CustomMode",
       "Light_Headlight",
       "Light_Left_Indicator",
       "Light_Right_Indicator",
       "Light_BPS_Strobe",
       "Light_Brakelight"
      ]
     },
     "buffer": 1
    }
   ]
  },
  {
   "title": "Lighting Canopy",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 148 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "channel": "stream/telemetry/674",
     "filter": {
      "fields": [
       "Light_CustomMode",
       "Light_Headlight",
       "Light_Left_Indicator",
       "Light_Right_Indicator",
       "Light_BPS_Strobe",
       "Light_Brakelight"
      ]
     },
     "buffer": 1
    }
   ]
  },
  {
   "title": "Front LED Currents",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 152 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry_main\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"670\")\n  |> filter(fn: (r) => r._field == \"Lighting_Addr_LED_Current\")\n  |> filter(fn: (r) => r.vehicle == \"HighNoon\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    },
    {
     "query": "from(bucket: \"telemetry_main\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"670\")\n  |> filter(fn: (r) => r._field == \"Lighting_LED0_Current\")\n  |> filter(fn: (r) => r.vehicle == \"HighNoon\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    },
    {
     "query": "from(bucket: \"telemetry_main\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"670\")\n  |> filter(fn: (r) => r._field == \"Lighting_LED1_Current\")\n  |> filter(fn: (r) => r.vehicle == \"HighNoon\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    }
   ]
  },
  {
   "title": "Left LED Currents",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 152 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry_main\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"671\")\n  |> filter(fn: (r) => r._field == \"Lighting_Addr_LED_Current\")\n  |> filter(fn: (r) => r.vehicle == \"HighNoon\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    },
    {
     "query": "from(bucket: \"telemetry_main\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"671\")\n  |> filter(fn: (r) => r._field == \"Lighting_LED0_Current\")\n  |> filter(fn: (r) => r.vehicle == \"HighNoon\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    },
    {
     "query": "from(bucket: \"telemetry_main\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"671\")\n  |> filter(fn: (r) => r._field == \"Lighting_LED1_Current\")\n  |> filter(fn: (r) => r.vehicle == \"HighNoon\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    }
   ]
  },
  {
   "title": "Rear LED Currents",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 158 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry_main\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"672\")\n  |> filter(fn: (r) => r._field == \"Lighting_Addr_LED_Current\")\n  |> filter(fn: (r) => r.vehicle == \"HighNoon\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    },
    {
     "query": "from(bucket: \"telemetry_main\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"672\")\n  |> filter(fn: (r) => r._field == \"Lighting_LED0_Current\")\n  |> filter(fn: (r) => r.vehicle == \"HighNoon\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    },
    {
     "query": "from(bucket: \"telemetry_main\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"672\")\n  |> filter(fn: (r) => r._field == \"Lighting_LED1_Current\")\n  |> filter(fn: (r) => r.vehicle == \"HighNoon\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    }
   ]
  },
  {
   "title": "Right LED Currents",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 158 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry_main\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"673\")\n  |> filter(fn: (r) => r._field == \"Lighting_Addr_LED_Current\")\n  |> filter(fn: (r) => r.vehicle == \"HighNoon\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    },
    {
     "query": "from(bucket: \"telemetry_main\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"673\")\n  |> filter(fn: (r) => r._field == \"Lighting_LED0_Current\")\n  |> filter(fn: (r) => r.vehicle == \"HighNoon\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    },
    {
     "query": "from(bucket: \"telemetry_main\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"673\")\n  |> filter(fn: (r) => r._field == \"Lighting_LED1_Current\")\n  |> filter(fn: (r) => r.vehicle == \"HighNoon\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    }
   ]
  },
  {
   "title": "Canopy LED Currents",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 164 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry_main\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"674\")\n  |> filter(fn: (r) => r._field == \"Lighting_Addr_LED_Current\")\n  |> filter(fn: (r) => r.vehicle == \"HighNoon\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    },
    {
     "query": "from(bucket: \"telemetry_main\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"674\")\n  |> filter(fn: (r) => r._field == \"Lighting_LED0_Current\")\n  |> filter(fn: (r) => r.vehicle == \"HighNoon\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    },
    {
     "query": "from(bucket: \"telemetry_main\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"674\")\n  |> filter(fn: (r) => r._field == \"Lighting_LED1_Current\")\n  |> filter(fn: (r) => r.vehicle == \"HighNoon\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    }
   ]
  },
  { "title": "Display & Cameras", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 170 } },
  {
   "title": "Cabin / Cameras",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 171 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "channel": "stream/telemetry/680",
     "filter": {
      "fields": [
       "Display_FrameRate",
       "Camera_Status_Backup",
       "Camera_Status_Left",
       "Camera_Status_Right"
      ]
     },
     "buffer": 1
    },
    { "channel": "stream/telemetry/700", "filter": { "fields": [ "Telemetry_Heartbeat" ] }, "buffer": 1 }
   ]
  },
  {
   "title": "Telemetry HB age",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 175 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry_main\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._measurement == \"700\")\n  |> filter(fn: (r) => r._field == \"Telemetry_Heartbeat\")\n  |> filter(fn: (r) => r.vehicle == \"HighNoon\")\n  |> group()\n  |> last()\n  |> map(fn: (r) => ({ _value: (float(v: uint(v: now())) - float(v: uint(v: r._time))) / 1000000000.0 }))\n  |> keep(columns: [\"_value\"])"
    }
   ]
  },
  { "title": "Data Freshness", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 179 } },
  {
   "title": "Driver Inputs age",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 180 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry_main\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._measurement == \"60\")\n  |> filter(fn: (r) => r._field == \"Ignition_Off\")\n  |> filter(fn: (r) => r.vehicle == \"HighNoon\")\n  |> group()\n  |> last()\n  |> map(fn: (r) => ({ _value: (float(v: uint(v: now())) - float(v: uint(v: r._time))) / 1000000000.0 }))\n  |> keep(columns: [\"_value\"])"
    }
   ]
  },
  {
   "title": "Pedals age",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 180 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry_main\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._measurement == \"50\")\n  |> filter(fn: (r) => r._field == \"AccelPedal_Main_Pos\")\n  |> filter(fn: (r) => r.vehicle == \"HighNoon\")\n  |> group()\n  |> last()\n  |> map(fn: (r) => ({ _value: (float(v: uint(v: now())) - float(v: uint(v: r._time))) / 1000000000.0 }))\n  |> keep(columns: [\"_value\"])"
    }
   ]
  },
  {
   "title": "Steering age",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 180 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry_main\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._measurement == \"2B0\")\n  |> filter(fn: (r) => r._field == \"LWS_Angle\")\n  |> filter(fn: (r) => r.vehicle == \"HighNoon\")\n  |> group()\n  |> last()\n  |> map(fn: (r) => ({ _value: (float(v: uint(v: now())) - float(v: uint(v: r._time))) / 1000000000.0 }))\n  |> keep(columns: [\"_value\"])"
    }
   ]
  },
  {
   "title": "Lighting Front age",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 180 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry_main\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._measurement == \"670\")\n  |> filter(fn: (r) => r._field == \"Lighting_Board_Fault\")\n  |> filter(fn: (r) => r.vehicle == \"HighNoon\")\n  |> group()\n  |> last()\n  |> map(fn: (r) => ({ _value: (float(v: uint(v: now())) - float(v: uint(v: r._time))) / 1000000000.0 }))\n  |> keep(columns: [\"_value\"])"
    }
   ]
  }
 ]
}